### PR TITLE
travis: PHP 7.0 nightly added; simplified

### PR DESCRIPTION
**Pull request by TomasVotruba**
For PHP 7.0 see http://docs.travis-ci.com/user/languages/php/#PHP-7

This should be more readable and DRY.

Also, download ocular.phar only when needed.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@TomasVotruba there seems to be a syntax error in the travis.yml

**Comment by TomasVotruba** [comment]
@frankdejonge Wow, you're too fast for me :) give me sec.

**Comment by TomasVotruba** [comment]
@frankdejonge So travis allows [multiline statements only in standalone files](https://github.com/travis-ci/travis-ci/issues/497#issuecomment-5879990).

I've added those in the same way as in [Mockery](https://github.com/padraic/mockery/blob/master/.travis.yml).

Now it's finished and passing.

**Comment by TomasVotruba** [comment]
Ping @frankdejonge

**Comment by TomasVotruba** [comment]
Closing in favor of #479

**Comment by frankdejonge** [comment]
@TomasVotruba thanks!

**Pull request closed without merging**
