### PR TITLE
Allow defining custom permissions for the Local adapter.

### PR DESCRIPTION
**Pull request by twistor**
I decided to make a new member variable, rather than change the existing static $permissions in case subclasses are using that.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@twistor looks good! Could you add this to the changelog too?

**Comment by bcat-eu** [comment]
@twistor any way to change permissions globally after the class was instantiated? Same as in constructor but not on file or directory basis

**Comment by frankdejonge** [comment]
@bcat-eu I think altering this after construction is a bad idea, but what's you use-case?

**Comment by bcat-eu** [comment]
@frankdejonge laravel instantiates the class behind the scenes, if they will not change the code so that permissions are defined explicitly then defaults will be set and I'd have to update them at run time or extend the driver (that works already)

**Comment by frankdejonge** [comment]
@bcat-eu I think, when this is released a more viable option would be to ask if Taylor allows this to be configured for the local driver. Or send a PR his way.

**Comment by bcat-eu** [comment]
@frankdejonge all set, thanks for the support

**Comment by PatrickRose** [comment]
Ping @twistor / @frankdejonge: Is there an update for this PR. A project I'm working on might need this.

**Comment by frankdejonge** [comment]
@PatrickRose I'll get this ready for a release tonight (amsterdam time).

**Comment by PatrickRose** [comment]
@frankdejonge Thanks! :+1:

**Pull request merged**
