### PR TITLE
Memcached constructor signature optimization, removed excess use

### PR DESCRIPTION
**Pull request by creocoder**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@creocoder you say `optimisation`, but I only see a preference in coding style here. Is there any benefit of using this way?

**Comment by GrahamCampbell** [comment]
I don't see the point in this.

**Comment by creocoder** [comment]
> Is there any benefit of using this way?

> I don't see the point in this.

I can ask same question :) Import class to namespace just to not use FQN one time. Benefits? **Less code, same result**.

**Comment by GrahamCampbell** [comment]
It's a preferred code style.

**Comment by GrahamCampbell** [comment]
:-1: on merging this.

**Comment by frankdejonge** [comment]
I'd like to keep the same style across the project, which is basically: import all the things.

**Comment by creocoder** [comment]
I agree with code stype in all other cases. But this one looks like exception (collision between names, need aliasing) because its really make code hard to read. Another possible solutions is to rename main class and use Memcached without aliasing it.

**Comment by frankdejonge** [comment]
@creocoder in the community at large it's very common to use aliases like this to prevent naming collisions. For instance, in the symfony community when creating a console application, the Application class is often aliased to BaseApplication for the same reasons.

**Comment by creocoder** [comment]
@frankdejonge Ok, thanks for explaination. I think Memcached class name is good from practical point of view and seems it was the only way to support codestyle. I mean original code.

**Comment by frankdejonge** [comment]
@creocoder you're welcome. Thank you for showing an interest and for wanting to contribute!

**Pull request closed without merging**
