### PR TITLE
[WIP] Refactor/cacheless filesystem: 1.0

### PR DESCRIPTION
**Pull request by frankdejonge**
This PR represents the move towards 1.0.
Main pain-points in the 0.x series were:

* Caching in the Filesystem class
* Stream caching (which creates unexpected behaviour)
* Filesystem tests were a mess.
* Adapters with third-party deps were included.
* The Filesystem class was too damn big.

This PR (along with new repo's) will fix all of these things. Adapters are moved out when they have third-party dependencies. Caching is moved into an adapter decorator. Filesystem helper methods are moved into plugins.

This all has (already) had some stunning effects on the code quality and maintainability. The main entry point, the Filesystem class, had a Scrutinizer grade of F. At the time of writing this is now a B.

### CODE REVIEW

**Comment by barryvdh** [comment]
Why is the cached adapter a seperate package? That doesn't have dependancies yet, right? (except for code coverage)

Nice changes :)

**Comment by frankdejonge** [comment]
@barryvdh the case adapters are also going to be moved out. It'll allow for a way cleaner API internally and better dependency management.

**Comment by creocoder** [comment]
@GrahamCampbell, @frankdejonge Guys, what about \League\Flysystem\Adapter\Zip? Seems it also moved to separate repo, but changelog.md does not contains information about that and adapter is still here.

**Comment by GrahamCampbell** [comment]
Still wip. :)

**Comment by GrahamCampbell** [comment]
Is this good for merging?

**Pull request merged**
