### PR TITLE
Add missing AWS SSE-C Options

### PR DESCRIPTION
**Pull request by amenophis**
Hi,
Some options are missing to allow using AWS SSE-C with copy method.

Thanks

### CODE REVIEW

**Comment by amenophis** [comment]
Thanks @frankdejonge :pray: 
Do you know when we could expect a release ?

**Comment by frankdejonge** [comment]
Tonight at the latest 👌

**Comment by amenophis** [comment]
Hi @frankdejonge 
Any news about the release ?

Thanks :pray:

**Comment by amenophis** [comment]
@frankdejonge I will push a new PR in a couple of minute because I pushed a bad branch ...

Please wait to create the new release :pray:

**Pull request merged**
