### PR TITLE
Added more methods to File class. Tests included.

### PR DESCRIPTION
**Pull request by CarsonF**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@CarsonF awesome stuff! Could you look at more tests for the logical paths? Seems like some are missing: https://travis-ci.org/thephpleague/flysystem/jobs/47876099#L247

**Comment by CarsonF** [comment]
Do you mean add tests for the other methods that aren't tested to complete code coverage?

**Comment by CarsonF** [comment]
Added more tests. Code coverage for File is now 100%. Ready to merge?

**Comment by CarsonF** [comment]
@frankdejonge Do I need to buy you a :beer:? :smile:

**Comment by CarsonF** [comment]
Thanks @frankdejonge!

**Comment by frankdejonge** [comment]
@CarsonF thank you for the contribution!

**Pull request merged**
