### PR TITLE
Allow users of StreamedReadingTrait to determine type of stream and fix docs.

### PR DESCRIPTION
**Pull request by twistor**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@twistor wouldn't you then just not use this trait and implement the `readStream` differently? There's not a lot of logic in there.

**Comment by twistor** [comment]
That's true. What I really wanted to do was change it to php://temp and fix the docs.

**Comment by twistor** [comment]
It seems odd to have the string in memory, and then write it to a file.

**Comment by frankdejonge** [comment]
@twistor we could also use `fopen('php://memory', 'r')`?

**Comment by frankdejonge** [comment]
@twistor since we already have the string in memory when we use `php://memory` it'll always be in mem, the temp will write to file over a certain threshold.

**Comment by twistor** [comment]
@frankdejonge I thought about that. I was worried about making a copy of `contents` if it is large.

**Comment by frankdejonge** [comment]
Makes sense, let's go with this 👍

**Pull request merged**
