### PR TITLE
Robust getStreamSize

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@GrahamCampbell please change it to return `null` instead of throwing an exception and add this test case for the Util class:

```php
    public function testStreamSizeForUrl()
    {
        $stream = \fopen('https://flysystem.thephpleague.com/img/flysystem.svg', 'r');
        $this->assertNull(Util::getStreamSize($stream));
        fclose($stream);
    }
```

**Comment by GrahamCampbell** [comment]
Sure. For v2's design, I wonder how you would think about using the `Maybe` pattern, for robustness. Since, people probably calling this code will end up treating null as 0.

**Comment by GrahamCampbell** [comment]
https://github.com/schmittjoh/php-option is a long standing PHP implementation of this, used by phpdotenv under the hood.

**Comment by frankdejonge** [comment]
@GrahamCampbell for 2.0 the behaviour will probably be to omit any size optimisations as well, but the interface won't be public like now.

**Comment by frankdejonge** [comment]
Released as 1.0.62 (this PR build fails because of the missing branch), master is green.

**Pull request merged**
