### PR TITLE
[WIP] Fixed travis config

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This was not ready yet.

**Comment by GrahamCampbell** [comment]
I opened the PR in other to trigger the build.

**Comment by frankdejonge** [comment]
@GrahamCampbell please add some information for the next one. If I don't see anything to not merge it, I won't know. For me it's just an open pull request.

**Comment by GrahamCampbell** [comment]
It said WIP in the title.

**Pull request merged**
