### PR TITLE
Rename ContentMD5 to AddContentMD5 for AWS

### PR DESCRIPTION
**Pull request by alexndlm**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@alexndlm any chance you can link to the relevant docs that highlight this change?

**Comment by alexndlm** [comment]
@frankdejonge , please see here https://github.com/aws/aws-sdk-php/blob/0a910d2b35e7087337cdf3569dc9b6ce232aafba/src/S3/S3Client.php#L1040

**Comment by alexndlm** [comment]
@frankdejonge, any chances to merge this?

**Comment by mattbartel** [comment]
I don't think this is the correct change for this feature. According to the `aws-sdk-php` code in [MultpartUploader.php](https://github.com/aws/aws-sdk-php/blob/18c0ebd71d3071304f1ea02aa9af75f95863177a/src/S3/MultipartUploader.php#L130), [ObjectUploader.php](https://github.com/aws/aws-sdk-php/blob/18c0ebd71d3071304f1ea02aa9af75f95863177a/src/S3/ObjectUploader.php#L64), and [Transfer.php](https://github.com/aws/aws-sdk-php/blob/18c0ebd71d3071304f1ea02aa9af75f95863177a/src/S3/Transfer.php#L140), it's the `add_content_md5` option that should be added.  I don't see any code in the SDK looks for the `ContentMD5` or `AddContentMD5` flags directly so I think they can just be removed.  I submitted another pull request here: https://github.com/thephpleague/flysystem/pull/1774

**Comment by alexndlm** [comment]
@mattbartel thanks.
c94490e273b3f979884bffadcacbe7b1


Closed in favor of https://github.com/thephpleague/flysystem/pull/1774

**Pull request closed without merging**
