### PR TITLE
Fix incorrect argument amount for S3 fileExists()

### PR DESCRIPTION
**Pull request by SergeyPodgornyy**
image
image

### CODE REVIEW

**Comment by SergeyPodgornyy** [comment]
@frankdejonge could you please see this bugfix to the code of S3? :pray: This bug causes some problems with the production application I maintain.

Also, it would be really valuable to update sub-repo [thephpleague/flysystem-aws-s3-v3](https://github.com/thephpleague/flysystem-aws-s3-v3) with this fix

**Comment by SergeyPodgornyy** [comment]
Thank you @frankdejonge :bowing_man: Could you also create a new release tag in both repositories to be able to download the fix, please? :pray:

**Comment by frankdejonge** [comment]
It's released as 3.12.2

**Comment by SergeyPodgornyy** [comment]
Thank you

**Pull request merged**
