### PR TITLE
Implement copy and rename plugins that overwrite destination.

### PR DESCRIPTION
**Pull request by twistor**
RE: #292 

Trying to extend the interface, or default implementation, leads to problems.

Here's an implementation via plugins.

### CODE REVIEW

**Comment by twistor** [comment]
I haven't actually tested this.

Will write tests if we decide this is the direction to go.

**Comment by GrahamCampbell** [comment]
Pretty nice. :+1:

**Comment by frankdejonge** [comment]
@twistor I like it! 👍

**Comment by twistor** [comment]
Added return value checking for the delete() call. Makes things awkward.

**Comment by franksl** [comment]
Hi,
Is it possible to forceCopy between two filesystem in a MountManager? I tried adding the plugin to the MountManager instance but plugins are called on a specific filesystem (the one indicated by the first prefix)
Thanks,
Frank

**Comment by frankdejonge** [comment]
Hi @franksl, you'd need to create specific ones for the mount manager, because while the concept is the same, the actual implementation can't be made portable within the same plugin.

**Comment by franksl** [comment]
Ok, thanks a lot for the answer, I'll try to work around it.

**Comment by basz** [comment]
I don't believe a forcedCopy for a MountManager was ever implemented right?

**Comment by frankdejonge** [comment]
@basz no they weren't. However I'm thinking of making deletes idempotent, which makes it possible to do:

```php
$fs->delete($destination);
$fs->copy($source, $destination);
```

Which IMO eliminates the need for forcesCopy entirely.

**Pull request merged**
