### PR TITLE
AsyncS3: throw FilesystemOperationFailed exceptions in case upload or listContent fails

### PR DESCRIPTION
**Pull request by glaubinix**
Currently, the async s3 adapter throws a `Symfony\Component\HttpClient\Exception\TransportException` in case a request fails. To match other adapters, this PR converts those exceptions to `FilesystemOperationFailed`.

### CODE REVIEW

**Comment by frankdejonge** [comment]
Hi @glaubinix, could you convert the test from generated mocks to the S3ClientStub like the other tests? The rest looks like a nice contribution, much appreciated.

**Comment by glaubinix** [comment]
Sure thing! Adjusted the test to match the other tests.

**Comment by frankdejonge** [comment]
Running the tests now :) will release when green

**Comment by glaubinix** [comment]
Thank you!

**Comment by frankdejonge** [comment]
Out for a few, but will tag a release this afternoon

**Pull request merged**
