### PR TITLE
`getAdapter()` support stacked type adapter

### PR DESCRIPTION
**Pull request by nao-pon**
Like a CachedAdapter.

ref. #412

### CODE REVIEW

**Comment by frankdejonge** [comment]
Same reason as before. The Filesystem will only get the underlying adapter, it's the user's own responsibility to fetch an underlying resource if needed. This doesn't fix the issue, nor is it the responsibility of the Filesystem class to do so.

**Comment by nao-pon** [comment]
Thank you, I understand.

**Comment by frankdejonge** [comment]
I'll look into writing tests for the other PR soon.

**Comment by nao-pon** [comment]
I really appreciate it. :-)

**Pull request closed without merging**
