### PR TITLE
Added ico => image/x-icon mime type

### PR DESCRIPTION
**Pull request by adamhopkinson**
Needed for some code I'm working on - all other image types I need are represented, but not ico files.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This should be added in the correct position, alphabetically, rather than being dumped at the end.

**Comment by adamhopkinson** [comment]
@GrahamCampbell I did consider this, but the array is neither order by key nor value so I assumed my addition should go at the end.

**Comment by frankdejonge** [comment]
Thanks @adamhopkinson, it's released as 1.0.68.

**Comment by adamhopkinson** [comment]
Thanks @frankdejonge

**Pull request merged**
