### PR TITLE
WIP: Assert that all filesystems throws exception on unknown mime type

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@Lctrs Hi, will you finish this PR or do you want to me to take it over?

**Comment by Lctrs** [comment]
Hi @frankdejonge 

I would like to finish it.

Little context on why : 

I encountered a `TypeError` exception when calling `Filesystem::mimeType()` method because the underlying FTPAdapter returned a `null` mime type on the test file provided in this PR.

I have a version on my computer where it's fixed for the FTP and SFTP adapters.

Problem : the test don't pass for the local and in memory adapters because they do return a `text/plain` mime type for the above-mentioned file.

I can't find a file which would make them return `null` as well. Do you have any idea ?

**Comment by frankdejonge** [comment]
@Lctrs I've got a way to test that. We can use an alternate implementation of the mime-type detector that doesn't use finfo.

```php
use League\Flysystem\Filesystem;
use League\Flysystem\Local\LocalFilesystemAdapter;
use League\MimeTypeDetection\EmptyExtensionToMimeTypeMap;
use League\MimeTypeDetection\ExtensionMimeTypeDetector;

$detector = new ExtensionMimeTypeDetector(new EmptyExtensionToMimeTypeMap());
$filesystem = new Filesystem(new LocalFilesystemAdapter(__DIR__, null, LOCK_EX, LocalFilesystemAdapter::DISALLOW_LINKS, $detector));

$filesystem->mimeType('/composer.lock');
```

**Comment by frankdejonge** [comment]
@Lctrs I'll pull this into a local branch and merge with the local case. Thanks for uncovering this.

**Comment by frankdejonge** [comment]
@Lctrs I've fixed the other cases and merged them from the other branch. Thank you so much for trying the release candidate and for highlighting this issue.

**Comment by Lctrs** [comment]
No thanks to you for this V2. It has never been easier to work with FTP.

**Pull request closed without merging**
