### PR TITLE
fix docs

### PR DESCRIPTION
**Pull request by akshay-kh**
* fix symfony logo path.
    * make html/css text as code view.

related to #1073

### CODE REVIEW

**Comment by frankdejonge** [comment]
Hi! Could you remove the fixes for the logo's? Those seem to be fine on the docs. What issue did you experience with it?

**Comment by akshay-kh** [comment]
in github i got these broken links.
Annotation 2019-10-12 205855

**Comment by frankdejonge** [comment]
Those links are not supposed to work there, but should be viewed from https://flysystem.thephpleague.com/

**Comment by akshay-kh** [comment]
oh ok i have reverted changes to images please review.

**Comment by akshay-kh** [comment]
@frankdejonge i have removed logo fix.

**Pull request merged**
