### PR TITLE
Doc suggestions

### PR DESCRIPTION
**Pull request by driesvints**
Here's just a few suggestions. I removed the backticks in the title because those looked a little bit weird.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@driesvints what's the reason for the `~` => `^` change? From what I get from the composer docs, the `~` is just fine, or am I missing something?

**Comment by GrahamCampbell** [comment]
It tells users that flysystem is following semver.

**Comment by frankdejonge** [comment]
@GrahamCampbell the other one is semver too though? I'm confused.

**Comment by frankdejonge** [comment]
https://getcomposer.org/doc/articles/versions.md#tilde-version-range- is even states it's the most useful for semver projects. The `^` seems more for people who want to get at least a certain patch version as well, so for an x.x.x version, not a x.x one.

**Comment by GrahamCampbell** [comment]
Only `^` is "the semver operator". For example, `~0.4` or `~4.2.1` will not have the effect of "give me the latest version compatible with the API at 0.4 or 4.2.1, respectively".

**Comment by frankdejonge** [comment]
Are you sure, @GrahamCampbell, I read the docs in a different way.

from the docs:

The ~ operator is best explained by example: ~1.2 is equivalent to >=1.2 <2.0.0, while ~1.2.3 is equivalent to >=1.2.3 <1.3.0. As you can see it is mostly useful for projects respecting semantic versioning. A common usage would be to mark the minimum minor version you depend on, like ~1.2 (which allows anything up to, but not including, 2.0). Since in theory there should be no backwards compatibility breaks until 2.0, that works well. Another way of looking at it is that using ~ specifies a minimum version, but allows the last digit specified to go up.

**Comment by GrahamCampbell** [comment]
Yes, I am sure. For the most clarity, look at their tests. ;)

**Comment by GrahamCampbell** [comment]
My first example was 0.x range on purpose, since the behaviour is the same on 1.x.

**Comment by frankdejonge** [comment]
That shit is not clearly explained in the composer docs then ... hmm.

**Comment by GrahamCampbell** [comment]
I think it is in the docs? It says:

> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.

**Comment by GrahamCampbell** [comment]
Where as `~` does nothing special, so will let you have 0.5.0, given `~0.3`.

**Comment by frankdejonge** [comment]
Gotcha, so for this upgrade and further on it doesn't matter. Thanks for the clarification anyway 👍

**Comment by driesvints** [comment]
@frankdejonge part because of the reasons stated by Graham above but mainly because it's the more commonly used convention.

**Pull request merged**
