### PR TITLE
Update Ftp.php

### PR DESCRIPTION
**Pull request by exy**

### CODE REVIEW

**Comment by twistor** [comment]
What problem are you trying to fix with this patch?

**Comment by exy** [comment]
Hello,

There is a difference in behavior between, at least, 2 adapters : FTP & SFTP.
Here is a sample code :

```
$adapterFTP = new \League\Flysystem\Adapter\Ftp([
                    'host' => HOST,
                    'username' => USER,
                    'password' => PASSWORD,
                    'port' => 21,
                    'root' => '/path/to/remote/',
                    'passive' => true,
                    'ssl' => false,
                    'timeout' => 10
                ]);
$adapterSFTP = new \League\Flysystem\Sftp\SftpAdapter([
                    'host' => HOST,
                    'username' => USER,
                    'password' => PSSWORD,
                    'port' => 22,
                    'privateKey' => null,
                    'root' => '/path/to/remote/',
                    'timeout' => 10,
                ]);

$filesystemFTP = new Filesystem($adapterFTP);
$filesystemSFTP = new Filesystem($adapterSFTP);

$file = '/path/to/local/file.csv'
$handler = fopen($file, 'r');
$filesystemSFTP->putStream(basename($file), $handler);
$filesystemFTP->putStream(basename($file), $handler);
fclose($handler);
```

**FTP has an exception :**
> exception 'UnexpectedValueException' with message 'ftp_chdir(): path/to/local/file.csv: No such file or directory'
> Stack trace:
> #0 [internal function]: {closure}(2, 'ftp_chdir(): ex...', '/var/www...', 350, Array)
> #1 /var/www/test/vendor/league/flysystem/src/Adapter/Ftp.php(350): ftp_chdir(Resource id #240, 'path/to/local/fi...')
> #2 /var/www/test/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(540): League\Flysystem\Adapter\Ftp->getMetadata('path/to/local/fi...')
> #3 /var/www/test/vendor/league/flysystem/src/Filesystem.php(56): League\Flysystem\Adapter\AbstractFtpAdapter->has('path/to/local/fi...')
> #4 /var/www/test/vendor/league/flysystem/src/Filesystem.php(400): League\Flysystem\Filesystem->has('path/to/local/fi...')
> #5 /var/www/test/vendor/league/flysystem/src/Filesystem.php(65): League\Flysystem\Filesystem->assertAbsent('path/to/local/fi...')
> #6 /var/www/test/src/Remote.php(81): League\Flysystem\Filesystem->write('/path/to/local/f...', 'avaevaevea...')

**Comment by twistor** [comment]
Well, those checks are the way they are for a reason.

We're not interested if the parent directory is a directory, we're trying to check if the path provided is a directory.

What PHP version are you using?

Since that `ftp_chdir` is silenced, you shouldn't be seeing any errors unless xdebug.scream is enabled. Either way though, it shouldn't throw an exception.

**Comment by exy** [comment]
I'm using **PHP 5.6.22**

**For the exception this is because of an error handler :**
> set\_error\_handler(function ($errno, $errstr) {
>    throw new UnexpectedValueException($errstr,$errno);
>});

php -i | grep xdebug.scream :
>xdebug.scream => Off => Off

---

**I have tested with this :**

*'/remote/path' exist on server*

1. With no 'root' set in the FTP construct adapter :

 + $filesystemFTP->putStream('/remote/path/file.csv', $handler)
    
> error : "ftp_chdir(): remote/path/file.csv: No such file or directory"

2. With 'root' set in the FTP construct adapter :

```php
$adapterFTP = new \League\Flysystem\Adapter\Ftp([
                    'host' => HOST,
                    'username' => USER,
                    'password' => PASSWORD,
						'port' => 21,
                    'root' => '/remote/path/',
                    'passive' => true,
                    'ssl' => false,
                    'timeout' => 10
                ]);
$filesystemFTP = new Filesystem($adapterFTP);
```

 + $filesystemFTP->putStream('file.csv', $handler)

> error : "ftp_chdir(): file.csv: No such file or directory"

With SFtpAdapter this works.

As I'm using an API (Flysystem), I'm expecting that each adapters works the same way.

**Comment by twistor** [comment]
Well, your exception handler is the problem.

Both adapters work the same way, from the outside. They are implemented differently because they use different APIs. There's no good way to check for the existence of a directory using PHP's native FTP api. You just have to try to cd into it, and hide the warning. This is what's happening currently.

Your exception handler is going to cause a lot more problems, if you use other libraries as well.

**Pull request closed without merging**
