### PR TITLE
Fix SftpAdapter not overwriting on move

### PR DESCRIPTION
**Pull request by kynx**
Currently the `SftpAdapter` doesn't overwrite existing files when moving, unlike other adapters. This PR adds that ability.

### CODE REVIEW

**Comment by kynx** [comment]
> Moving and copying are both deterministic operations. This means they will always overwrite the target location, and parent directories are always created (if and when needed).

(from https://flysystem.thephpleague.com/docs/usage/filesystem-api/ )

Judging by the failing tests this is based on some alternative facts 😉 But fixing the other adapters should probably be done in separate PRs.

**Comment by kynx** [comment]
OK, I've moved the `moving_a_file_and_overwriting()` and `moving_a_directory_and_overwriting()` tests to `SftpAdapterTest` so that the other adapter tests no longer fail and this will stand a chance of getting merged. Once the other adapters are fixed these tests should be added back to `FilesystemAdapterTestCase`

**Comment by kynx** [comment]
@frankdejonge Apologies, I totally missed that this had conflicts. Those are resolved now.

**Comment by SamMousa** [comment]
@kynx I'm gonna try and get `posix_rename` support in PHPSecLib.

https://github.com/phpseclib/phpseclib/issues/2024

Just an FYI. If that works out we should support it in this adapter as well (and fallback to the manual solution if not supported).

Edit: 
I've also implemented a generic solution for all adapters here: https://github.com/collecthor/flysystem-adapters/pull/7
Of course this is suboptimal but it provides a path forward at least.

**Comment by kynx** [comment]
@SamMousa great idea with the `posix_rename` stuff! I've always felt a little nervous around the phpseclib code :smile: 

The generic adapter solution is also a worthwhile compromise - I should have thought of something like that.

TBH I'd completely forgotten this PR, but just checked and oops - it's been in production on one project for over a year! Got to find some tool to send reminders when something lurks in composer's' `repositories` too long :wink:

**Comment by SamMousa** [comment]
@kynx posix_rename has been merged: https://github.com/phpseclib/phpseclib/pull/2029

Are you up for adding support to the sftp adapter?

**Pull request merged**
