### PR TITLE
Fix setRoot on AbstractFtpAdapter

### PR DESCRIPTION
**Pull request by The-Hasanov**
i use laravel filesystem but have problem if  i  change root folder first ftp use folder not changed
before fix:
        $storage->createDir('root');
        $storage->getDriver()->getAdapter()->setRoot($storage->getDriver()->getAdapter()->getRoot() . '/root');
        $storage->createDir('products');
folders:
  /root
  /products

after:
folders:
  /root
  /root/products

### CODE REVIEW

**Comment by frankdejonge** [comment]
The root is not supposed to be changed at runtime, you should create a new Filesystem for the next call.

**Comment by The-Hasanov** [comment]
but if i use 
$storage->exists('something');
before create products dir 
root folder automatically changed

**Comment by The-Hasanov** [comment]
after changed root  try create 8 folder only first folder not true path

**Comment by frankdejonge** [comment]
Correct, because if needs to change into directories to check if they exist and then reset the connection root which you're altered in the meanwhile. But as I said before, you need to create a new filesystem or just use the same filesystem without corrupting the root path. Just because something happens after you use it incorrectly that doesn't mean it's intended usage nor that I will support the use-case. I've now given you two alternatives, stated it's not intended usage and explained why your unintended usage had "worked" for you. Besides all that the ecosystem around flysystem doesn't support changing of root directories, so I'm closing this PR.

**Pull request closed without merging**
