### PR TITLE
Fix InMemory not overwriting on move

### PR DESCRIPTION
**Pull request by kynx**
This fixes the `InMemoryFilesystemAdapter` not copying or moving directories

### CODE REVIEW

**Comment by frankdejonge** [comment]
Can you make this strategy configurable via a constructor option? Otherwise this would be a major BC break and I do not want to cause that.

**Comment by kynx** [comment]
@frankdejonge Uh, OK. Guess the documentation should be updated to reflect the fact that not all adapters behave the same?

**Comment by kynx** [comment]
@frankdejonge Actually I might have got a little carried away with copying and moving directories. My initial problem was with the SFTP adapter not overwriting _files_ when moving after upgrading an old project from 1.x to 3.x. Looking back at the docs there is no mention of copying or moving directories.

I do think it's a bug that some adapters don't overwrite files on move - the docs clearly say they do. If I moved the directory stuff to a different PR targeting the next major, would that work?

**Comment by kynx** [comment]
@frankdejonge I've removed the directory copy / move stuff. This now just brings this adapter in line with the others, overwriting existing files on move.

Please let me know if you still think this needs a constructor arg for specifying this behaviour.

**Comment by SamMousa** [comment]
What's wrong with a new major release that deliberately breaks BC?

**Comment by tinect** [comment]
This looks like I managed it with my PR which got now released.
So this PR could be closed, couldn't it?

**Pull request closed without merging**
