### PR TITLE
[2.x] Refactor read interfaces to allow config

### PR DESCRIPTION
**Pull request by KDederichs**
Add optional config parameter to read interfaces to cover cases like descibed in #1318

### CODE REVIEW

**Comment by PaolaRuby** [comment]
Breaks all custom adapters, maybe default options setter on Aws Adapter, or arg on constructor?

**Comment by KDederichs** [comment]
You can't really set it for the whole adapter imo since it's possible for each object to have a different key.

**Comment by KDederichs** [comment]
Another solution that won't break existing custom interfaces would be to maybe add a new 'EncryptedFilesystem' interface and then implement the encryption/decryption logic directly on the filesystem adapters that support it?
Maybe that would be a better solution.

**Comment by KDederichs** [comment]
Ok I introduced that solution in #1325 so tell me which is the one you guys would prefer.

**Comment by Nyholm** [comment]
Thank you for this PR. Im afraid I cannot merge this. Modifying the method signature of the interface is a BC break. 

Thank you @PaolaRuby for the review. I agree with you. 
I'll close this PR and review the alternative in #1325.

**Pull request closed without merging**
